"""empty message

Revision ID: a4acfa652846
Revises: 
Create Date: 2023-09-17 20:41:00.899429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4acfa652846'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('babinje_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_grade', sa.String(length=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('babinje_item', schema=None) as batch_op:
        batch_op.drop_column('price_grade')

    # ### end Alembic commands ###
